- name: Adds gcloud key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adds gcloud repos
  apt_repository:
    repo: "deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main"
    update_cache: yes

- name: Installs google-cloud-sdk
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - google-cloud-sdk
    - python-pip
    - python-openssl

- name: Installs crcmod
  pip:
    name: crcmod

- name: Check if gcloud is configured
  shell: "gcloud config list core/account | grep {{ gcloud_service_email }} || echo 'NO'"
  changed_when: '"NO" in __gcloud_configured.stdout'
  register: __gcloud_configured

- name: Adds service account key
  template:
    src: servicekey.json.j2
    dest: /tmp/servicekey.json
  when: __gcloud_configured|changed

