- name: Create temporary file
  tempfile:
    state: file
    suffix: .json
  register: __gcloud_temp_key

- name: Adds service account key
  template:
    src: servicekey.json.j2
    dest: /tmp/servicekey.json

- name: Activate service account
  shell: "CLOUDSDK_PYTHON_SITEPACKAGES=1 gcloud auth activate-service-account {{ gcloud_service_email }} --key-file {{ __gcloud_temp_key.path }}"

- name: Sets default project
  command: gcloud config set core/project {{ gcloud_project_id }}
  when: gcloud_set_as_default

- name: Remove gcloud servicekey
  file:
    path: "{{ __gcloud_temp_key.path }}"
    state: absent


