- include: check_vars.yml
  when: gcloud_config_only
  tags: ["gcloud", "gcloud:check", "check"]

- include: gcloud.yml
  when: not gcloud_config_only
  tags: ["gcloud"]

- include: gcloud_config.yml
  tags: ["gcloud", "gcloud:config"]
