- include: check_vars.yml
  tags: ["gcloud", "gcloud:check", "check"]

- include: gcloud.yml
  when: not gloud_config_only
  tags: ["gcloud"]

- include: gcloud_config.yml
  tags: ["gcloud", "gcloud:config"]
