- include: check_vars.yml
  when: gcloud_config_only or gcloud_project_id is defined
  tags: ["gcloud", "gcloud:check", "check"]

- include: gcloud.yml
  when: not gcloud_config_only
  tags: ["gcloud"]

- include: gcloud_config.yml
  when: gcloud_key is defined
  tags: ["gcloud", "gcloud:config"]